- name: Playbook One
  hosts: localhost
  tasks:
    - name: "test"
      keepersecurity.keeper_secrets_manager.keeper_get:
        uid: "y1Qh00dkFgLcsVob2-fE7Q"
        file: "cert.pem"
      register: nginx_cert

    - name: "test"
      debug:
        var: nginx_cert