- name: Playbook One
  hosts: localhost
  tasks:
    - name: Get collection versions
      ansible.builtin.command: ansible-galaxy collection list keepersecurity.keeper_secrets_manager
      register: keeper_version

    - name: Print keepersecurity collection version
      ansible.builtin.debug:
        var: keeper_version.stdout

    - name: "test"
      keepersecurity.keeper_secrets_manager.keeper_get:
        uid: "y1Qh00dkFgLcsVob2-fE7Q"
        file: "cert.pem"
      register: nginx_cert

    - name: "test"
      debug:
        var: nginx_cert