---
- name: Playbook One
  hosts: all
  collections: 
    - keepersecurity.keeper_secrets_manager

  tasks:
    - name: Get login name. Loading record from Keeper Vault.
      keeper_get:
        uid: ipasPiqV0Lw1shtYK68_mg
        field: login
      register: my_login
      
    - name: Print login name
      debug:
        var: my_login.value
        verbosity: 0